events{
    worker_connections 1024;
}

http {

    upstream catalogo_services {server svc-catalogo:8091;}
    upstream miembros_services {server svc-miembros:8093;}
    upstream prestamos_services {server svc-prestamos:8092;}

    server{
        listen 80;

        location /api/catalogo/{
            proxy_pass http://catalogo_services/catalogo/;
            proxy_set_header Host $host;
        }

        location /api/miembros/{
            proxy_pass http://miembros_services/miembros/;
            proxy_set_header Host $host;
                }

        location /api/prestamos/{
            proxy_pass http://prestamos_services/prestamos/;
            proxy_set_header Host $host;
                }
    }

}